// Mirror backend permissions
export const PERMISSIONS = {
  PLAYER_CREATE: 'player.create',
  PLAYER_READ: 'player.read',
  PLAYER_UPDATE: 'player.update',
  PLAYER_DELETE: 'player.delete',
  PLAYER_EXPORT: 'player.export',
  
  CONTRACT_CREATE: 'contract.create',
  CONTRACT_READ: 'contract.read',
  CONTRACT_UPDATE: 'contract.update',
  CONTRACT_DELETE: 'contract.delete',
  CONTRACT_APPROVE: 'contract.approve',
  CONTRACT_REJECT: 'contract.reject',
  
  TRAINING_CREATE: 'training.create',
  TRAINING_READ: 'training.read',
  TRAINING_UPDATE: 'training.update',
  TRAINING_DELETE: 'training.delete',
  TRAINING_ASSIGN: 'training.assign',
  
  MEDICAL_CREATE: 'medical.create',
  MEDICAL_READ: 'medical.read',
  MEDICAL_UPDATE: 'medical.update',
  MEDICAL_VIEW_CONFIDENTIAL: 'medical.view_confidential',
  
  SCOUTING_CREATE: 'scouting.create',
  SCOUTING_READ: 'scouting.read',
  SCOUTING_UPDATE: 'scouting.update',
  SCOUTING_DELETE: 'scouting.delete',
  
  MATCH_CREATE: 'match.create',
  MATCH_READ: 'match.read',
  MATCH_UPDATE: 'match.update',
  MATCH_DELETE: 'match.delete',
  
  FINANCE_READ: 'finance.read',
  FINANCE_MANAGE: 'finance.manage',
  FINANCE_EXPORT: 'finance.export',
  
  LEGAL_CREATE: 'legal.create',
  LEGAL_READ: 'legal.read',
  LEGAL_UPDATE: 'legal.update',
  LEGAL_APPROVE: 'legal.approve',
  
  USER_CREATE: 'user.create',
  USER_READ: 'user.read',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_ASSIGN_ROLE: 'user.assign_role',
  
  TENANT_MANAGE: 'tenant.manage',
  
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',
  
  DOCUMENT_UPLOAD: 'document.upload',
  DOCUMENT_DELETE: 'document.delete',
  
  CHAT_SEND: 'chat.send',
  CHAT_READ: 'chat.read',
  CHAT_DELETE: 'chat.delete',
  
  PERFORMANCE_CREATE: 'performance.create',
  PERFORMANCE_READ: 'performance.read',
  PERFORMANCE_UPDATE: 'performance.update',
} as const;

export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Check if a role typically has a permission (client-side fallback)
 * This should be replaced with actual permission data from backend
 */
export function hasPermissionForRole(role: string, permission: PermissionType): boolean {
  const rolePermissions: Record<string, PermissionType[]> = {
    SUPER_ADMIN: Object.values(PERMISSIONS),
    
    OWNER: [
      PERMISSIONS.PLAYER_CREATE, PERMISSIONS.PLAYER_READ, PERMISSIONS.PLAYER_UPDATE,
      PERMISSIONS.CONTRACT_CREATE, PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_APPROVE,
      PERMISSIONS.TRAINING_READ,
      PERMISSIONS.MEDICAL_READ, PERMISSIONS.MEDICAL_VIEW_CONFIDENTIAL,
      PERMISSIONS.SCOUTING_READ,
      PERMISSIONS.MATCH_READ,
      PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_EXPORT,
      PERMISSIONS.LEGAL_READ,
      PERMISSIONS.USER_READ,
      PERMISSIONS.TENANT_MANAGE,
      PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT,
      PERMISSIONS.CHAT_READ,
    ],
    
    ADMIN: [
      PERMISSIONS.PLAYER_CREATE, PERMISSIONS.PLAYER_READ, PERMISSIONS.PLAYER_UPDATE,
      PERMISSIONS.CONTRACT_CREATE, PERMISSIONS.CONTRACT_READ,
      PERMISSIONS.TRAINING_CREATE, PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_UPDATE,
      PERMISSIONS.MEDICAL_READ,
      PERMISSIONS.SCOUTING_READ,
      PERMISSIONS.MATCH_READ,
      PERMISSIONS.LEGAL_CREATE, PERMISSIONS.LEGAL_READ,
      PERMISSIONS.USER_CREATE, PERMISSIONS.USER_READ, PERMISSIONS.USER_UPDATE,
      PERMISSIONS.REPORT_VIEW,
      PERMISSIONS.DOCUMENT_UPLOAD,
      PERMISSIONS.CHAT_SEND, PERMISSIONS.CHAT_READ,
    ],
    
    COACH: [
      PERMISSIONS.PLAYER_READ,
      PERMISSIONS.TRAINING_CREATE, PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_UPDATE,
      PERMISSIONS.MATCH_READ, PERMISSIONS.MATCH_UPDATE,
      PERMISSIONS.PERFORMANCE_READ,
      PERMISSIONS.CHAT_SEND, PERMISSIONS.CHAT_READ,
    ],
    
    SCOUT: [
      PERMISSIONS.PLAYER_READ,
      PERMISSIONS.SCOUTING_CREATE, PERMISSIONS.SCOUTING_READ, PERMISSIONS.SCOUTING_UPDATE,
      PERMISSIONS.DOCUMENT_UPLOAD,
    ],
    
    MEDICAL: [
      PERMISSIONS.PLAYER_READ,
      PERMISSIONS.MEDICAL_CREATE, PERMISSIONS.MEDICAL_READ, PERMISSIONS.MEDICAL_UPDATE,
      PERMISSIONS.MEDICAL_VIEW_CONFIDENTIAL,
      PERMISSIONS.TRAINING_READ,
    ],
    
    LEGAL: [
      PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_APPROVE,
      PERMISSIONS.LEGAL_CREATE, PERMISSIONS.LEGAL_READ, PERMISSIONS.LEGAL_UPDATE, PERMISSIONS.LEGAL_APPROVE,
      PERMISSIONS.DOCUMENT_UPLOAD,
    ],
    
    PLAYER: [
      PERMISSIONS.PLAYER_READ,
      PERMISSIONS.CONTRACT_READ,
      PERMISSIONS.TRAINING_READ,
      PERMISSIONS.MEDICAL_READ,
      PERMISSIONS.CHAT_SEND, PERMISSIONS.CHAT_READ,
    ],
  };
  
  return rolePermissions[role]?.includes(permission) || false;
}
