#!/usr/bin/env bash
# Coding assistants are tools, not co-authors: refuse a machine Co-Authored-By
# trailer or a "Generated with/by <assistant>" line — in a commit message, a PR
# title, or a PR body. (A co-author trailer puts the bot's avatar in the repo's
# contributor graph and on every commit.) Human co-authors are never refused.
#
# One narrow compatibility exception: a commit whose author is EXACTLY
# Dependabot keeps the exact trailer GitHub adds to its squash commits. Author
# metadata is spoofable, so this is compatibility, not authentication.
#
#   ./scripts/check-attribution.sh --message-file <file>
#   git rev-list <range> | ./scripts/check-attribution.sh --commits-stdin
#   ./scripts/check-attribution.sh --self-test
set -euo pipefail

S='[[:space:]]'
IDENTITY="((openai|gpt-[0-9.]+)$S+)?codex|chatgpt|(github$S+)?copilot|anthropic$S+claude|claude$S+(opus|sonnet|haiku|code|[0-9])|cursor($S+ai)?|devin$S+ai|aider|codeium|windsurf|tabnine|sourcegraph$S+cody|replit$S+agent|amazon$S+q|gemini$S+code$S+assist|cline|roo$S+code"
BOT_ADDRESS='\[bot\]|anthropic\.com|openai\.com|copilot@|cursor\.com|cognition\.ai|codeium|windsurf|tabnine|sourcegraph\.com|replit\.com|devin@|aider@'
GENERATOR="claude|anthropic|openai|chatgpt|gpt[- .]?[0-9]|codex|copilot|cursor|devin|aider|codeium|windsurf|tabnine|sourcegraph|cody|replit|amazon$S+q|gemini|cline|roo$S+code"
DEPENDABOT_NAME='dependabot[bot]'
DEPENDABOT_EMAIL='49699333+dependabot[bot]@users.noreply.github.com'
DEPENDABOT_TRAILER="^$S*co-authored-by:$S*dependabot\\[bot\\]$S*<49699333\\+dependabot\\[bot\\]@users\\.noreply\\.github\\.com>$S*$"

forbidden() { # stdin: a message → exit 0 when it carries forbidden attribution
  grep -Eiq \
    -e "^$S*co-authored-by:.*($BOT_ADDRESS)" \
    -e "^$S*co-authored-by:$S*($IDENTITY)[^<]*<" \
    -e "^$S*(🤖$S*)?generated($S+|-)(with|by)$S*:?$S+.*($GENERATOR)"
}

check_message_file() {
  if forbidden <"$1"; then
    echo "attribution: REFUSED — remove the machine Co-Authored-By / Generated-with line." >&2
    return 1
  fi
}

check_commits() { # stdin: commit SHAs
  local list records wanted sha name email body refused=0 seen=0
  list=$(mktemp "${TMPDIR:-/tmp}/attribution-list.XXXXXX")
  records=$(mktemp "${TMPDIR:-/tmp}/attribution-records.XXXXXX")
  grep -E '^[0-9a-f]{7,64}$' | sort -u >"$list" || true
  wanted=$(wc -l <"$list" | tr -d ' ')
  # ONE git process for the whole set: NUL-separated sha, name, email, message.
  if ! git log --no-walk=unsorted --stdin --format='%H%x00%an%x00%ae%x00%B%x00' <"$list" >"$records"; then
    rm -f "$list" "$records"
    echo "attribution: ERROR — git cannot read the commits; refusing closed." >&2
    return 2
  fi
  while IFS= read -r -d '' sha && IFS= read -r -d '' name &&
    IFS= read -r -d '' email && IFS= read -r -d '' body; do
    sha=${sha#$'\n'} # git ends each formatted record with a newline
    seen=$((seen + 1))
    if [ "$name" = "$DEPENDABOT_NAME" ] && [ "$email" = "$DEPENDABOT_EMAIL" ]; then
      body=$(grep -Eiv "$DEPENDABOT_TRAILER" <<<"$body" || true)
    fi
    # A here-string, not a pipe: `grep -q` exiting early must never turn a
    # match into SIGPIPE and, under pipefail, into a pass.
    if forbidden <<<"$body"; then
      echo "attribution: REFUSED — commit $sha carries assistant attribution." >&2
      refused=1
    fi
  done <"$records"
  rm -f "$list" "$records"
  if [ "$seen" -ne "$wanted" ]; then
    echo "attribution: ERROR — git described $seen of $wanted commits; refusing closed." >&2
    return 2
  fi
  [ "$refused" -eq 0 ] || {
    echo "  Rewrite those commits without the trailer (git rebase -i, reword)." >&2
    return 1
  }
  echo "attribution: $seen commit(s) clean"
}

self_test() {
  local pass=0 fail=0 tmp
  tmp=$(mktemp -d "${TMPDIR:-/tmp}/check-attribution.XXXXXX")
  trap 'rm -rf "$tmp"' RETURN
  message() { # message <exit> <label> <text>
    local want=$1 label=$2 got=0
    printf '%s\n' "$3" >"$tmp/msg"
    check_message_file "$tmp/msg" >/dev/null 2>&1 || got=$?
    if [ "$got" -eq "$want" ]; then printf '  ok      %s\n' "$label"; pass=$((pass + 1))
    else printf '  FAILED  %s (wanted %s, got %s)\n' "$label" "$want" "$got"; fail=$((fail + 1)); fi
  }
  echo "attribution — refused"
  message 1 "an assistant co-author" $'feat(api): x  [—]\n\nCo-Authored-By: Claude Opus 4.1 <noreply@anthropic.com>'
  message 1 "a tool co-author by address" $'fix(db): y  [—]\n\nco-authored-by: Helper <agent@openai.com>'
  message 1 "a bot co-author" $'fix(db): y  [—]\n\nCo-authored-by: some-bot[bot] <1+some-bot[bot]@users.noreply.github.com>'
  message 1 "a generated-with line" $'docs(repo): z  [—]\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)'
  message 1 "a generated-by line" $'docs(repo): z  [—]\n\nGenerated by GitHub Copilot'
  echo "attribution — allowed"
  message 0 "a plain message" $'feat(api): add login  [#42]\n\nExplains why.'
  message 0 "a human co-author named Claude" $'feat(api): x  [—]\n\nCo-Authored-By: Claude Monet <claude@example.com>'
  message 0 "prose that mentions a tool" $'docs(repo): compare copilot and cursor  [—]\n\nWe evaluated both.'

  git -C "$tmp" init -q
  git -C "$tmp" config user.name Dev
  git -C "$tmp" config user.email dev@example.com
  git -C "$tmp" commit -q --allow-empty -m 'chore(repo): clean  [—]'
  git -C "$tmp" -c user.name="$DEPENDABOT_NAME" -c user.email="$DEPENDABOT_EMAIL" commit -q --allow-empty \
    -m $'chore(repo): bump vite  [—]\n\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>'
  local got=0
  (cd "$tmp" && git rev-list HEAD | check_commits) >/dev/null 2>&1 || got=$?
  if [ "$got" -eq 0 ]; then printf '  ok      %s\n' "the exact Dependabot author keeps its trailer"; pass=$((pass + 1))
  else printf '  FAILED  %s\n' "the exact Dependabot author keeps its trailer"; fail=$((fail + 1)); fi
  git -C "$tmp" commit -q --allow-empty \
    -m $'chore(repo): spoof  [—]\n\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>'
  got=0
  (cd "$tmp" && git rev-list HEAD | check_commits) >/dev/null 2>&1 || got=$?
  if [ "$got" -eq 1 ]; then printf '  ok      %s\n' "anyone else carrying the bot trailer is refused"; pass=$((pass + 1))
  else printf '  FAILED  %s (got %s)\n' "anyone else carrying the bot trailer is refused" "$got"; fail=$((fail + 1)); fi

  printf '\n%s passed, %s failed\n' "$pass" "$fail"
  [ "$fail" -eq 0 ]
}

case "${1:-}" in
  --message-file) [ "$#" -eq 2 ] || exit 2; check_message_file "$2" ;;
  --commits-stdin) [ "$#" -eq 1 ] || exit 2; check_commits ;;
  --self-test) [ "$#" -eq 1 ] || exit 2; self_test ;;
  *) echo "usage: $0 --message-file <file> | --commits-stdin | --self-test" >&2; exit 2 ;;
esac
